# Generated by Django 3.1.5 on 2021-01-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='powerloom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plno', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=255)),
                ('qty_name', models.CharField(max_length=225)),
                ('size', models.CharField(choices=[('3672', '3672'), ('3060', '3060'), ('2754', '2754'), ('2448', '2448'), ('1827', '1827'), ('1218', '1218')], max_length=255)),
                ('image', models.ImageField(upload_to='photos/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Repair', 'Repair')], max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doprod', models.DateField(blank=True)),
                ('pcs', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('total_prod', models.CharField(blank=True, max_length=255, null=True)),
                ('plno', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.powerloom')),
            ],
        ),
    ]
