# Generated by Django 3.1.5 on 2021-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerloom',
            name='location',
            field=models.CharField(blank=True, choices=[('Factory1', 'Factory1'), ('Factory2&3', 'Factory2&3'), ('Factory5', 'Factory5')], max_length=255, null=True),
        ),
    ]
