# Generated by Django 3.1.5 on 2021-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_powerloom_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerloom',
            name='location',
            field=models.CharField(blank=True, choices=[('Factory1', 'Factory1'), ('Factory3', 'Factory3'), ('Factory4', 'Factory4'), ('Factory5', 'Factory5')], max_length=255, null=True),
        ),
    ]
